<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('entidades')->insert([
            ['nombre' => 'COMPUCONTA_SW_CC3', 'ip' => '10.142.0.5', 'port' => '5501','descripcion' => 'Sistema de informacion contable para Compuconta','db' => 'Compuconta','url' => 'https://compuconta-software.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'TUNARINO_CC3', 'ip' => '10.142.0.5', 'port' => '5502','descripcion' => 'Turnarino Almacen','db' => 'Compuconta','url' => 'http://hmorasurco.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'IEM_NORMAL_IN', 'ip' => '10.142.0.5', 'port' => '5503','descripcion' => 'IEM Normal Infraestructura','db' => 'Compuconta','url' => 'http://iemnormal.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'CLI_MONSERRATE_CC3', 'ip' => '10.142.0.5', 'port' => '5505','descripcion' => 'Clinica Monserrat - Activos fijos','db' => 'Compuconta','url' => 'http://montserrat.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ALC_RICAURTE_CC3_ACTIVOS', 'ip' => '10.142.0.5', 'port' => '5506','descripcion' => 'Alcaldia Municipal de Ricaurte - Activos fijos','db' => 'Compuconta','url' => 'http://alcricaurte.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'IPS_MUELLAMUES', 'ip' => '10.142.0.5', 'port' => '5507','descripcion' => 'IPS Muellamues','db' => 'Compuconta','url' => 'http://ipsmuellamues.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ESE_JUANPABLOII', 'ip' => '10.142.0.5', 'port' => '5508','descripcion' => 'ESE Juan Pablo II','db' => 'sistema','url' => 'https://ese-juanpabloii.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_MALLAMA', 'ip' => '10.142.0.5', 'port' => '5510','descripcion' => 'Alcaldia Municipal de Mallama','db' => 'sistema','url' => 'https://alcaldia-mallama.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_ROSARIO', 'ip' => '10.142.0.5', 'port' => '5511','descripcion' => 'Alcaldia Municipal de Rosario','db' => 'sistema','url' => 'https://alcaldia-rosario.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_FRANCISCOPIZARRO', 'ip' => '10.142.0.5', 'port' => '5512','descripcion' => 'Alcaldia Municipal de Francisco Pizarro','db' => 'sistema','url' => 'https://alcaldia-fcopizarro.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_BUESACO', 'ip' => '10.142.0.5', 'port' => '5513','descripcion' => 'Alcaldia Municipal de Buesaco','db' => 'sistema','url' => 'https://alcaldia-buesaco.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_CUASPUD', 'ip' => '10.142.0.5', 'port' => '5514','descripcion' => 'Alcaldia Municipal de Cuaspud','db' => 'sistema','url' => 'https://alcaldia-carlosama.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ESE_CAMILOCIFUENTES', 'ip' => '10.142.0.5', 'port' => '5515','descripcion' => 'Ese Camilo Cifuentes','db' => 'sistema','url' => 'https://ese-camilo-cifuentes.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ESE_MERCEDES', 'ip' => '10.142.0.5', 'port' => '5516','descripcion' => 'ESE Mercedes','db' => 'sistema','url' => 'https://ese-mercedes.compuconta.com/clave.php', 'version' => 'CC2'],
                ['nombre' => 'IEM_LIBERTAD_LAHORMIGA', 'ip' => '10.142.0.5', 'port' => '5517','descripcion' => 'IEM Libertad la Hormiga','db' => 'sistema','url' => 'http://iem-libertad-hormiga.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_SANPABLO', 'ip' => '10.142.0.5', 'port' => '5518','descripcion' => 'Alcaldia Municipal de San Pablo','db' => 'sistema','url' => 'https://alcaldia-sanpablo.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_ANCUYA', 'ip' => '10.142.0.5', 'port' => '5519','descripcion' => 'Alcaldia Municipal de Ancuya','db' => 'sistema','url' => 'https://alcaldia-ancuya.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_RICAURTE', 'ip' => '10.142.0.5', 'port' => '5520','descripcion' => 'Alcaldia Municipal de Ricaurte','db' => 'sistema','url' => 'https://alcaldia-ricaurte.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'UNIPA', 'ip' => '10.142.0.5', 'port' => '5555','descripcion' => 'UNIPA','db' => 'sistema','url' => 'https://unipa.compuconta.com/clave.php', 'version' => 'CC2'],
                ['nombre' => 'ESE_MALLAMA_CC3', 'ip' => '10.142.0.5', 'port' => '5522','descripcion' => 'ESE Mallama - Almacen','db' => 'Compuconta','url' => 'https://esemallama.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'CIUDAD_SOLAR_CC3', 'ip' => '10.142.0.5', 'port' => '5523','descripcion' => 'Ciudad Solar','db' => 'Compuconta','url' => 'https://ciudad-solar.compuconta.co/', 'version' => 'CC3'],
                ['nombre' => 'IEM_HERALDO-ROMERO', 'ip' => '10.142.0.5', 'port' => '5604','descripcion' => 'Iem Heraldo Romero Sanchez','db' => 'sistema','url' => 'https://iem_heraldo-romero.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_RICAURTE_CC3_IyC', 'ip' => '10.142.0.5', 'port' => '5525','descripcion' => 'Alcaldia Municipal de Ricaurte - Industria y Ccio','db' => 'Compuconta','url' => 'http://alcricaurteiyc.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ESE_LEIVA', 'ip' => '10.142.0.5', 'port' => '5527','descripcion' => 'ESE Leiva','db' => 'sistema','url' => 'http://ese-leiva.compuconta.co/clave.php', 'version' => 'CC2'],
                ['nombre' => 'ALC_PTOASIS_CC3', 'ip' => '10.142.0.5', 'port' => '5528','descripcion' => 'Alcaldia Municipal de Puerto Asis - Almacen CC3','db' => 'Compuconta','url' => 'http://alcptoasis.compuconta.com', 'version' => 'CC3'],
                ['nombre' => 'EMSERPUVAG', 'ip' => '10.142.0.5', 'port' => '5529','descripcion' => 'EMSERPUVAG','db' => 'Compuconta','url' => 'http://emserpuvag.compuconta.com', 'version' => 'CC3'],
                ['nombre' => 'CLI_PAREDES_CC3', 'ip' => '10.142.0.5', 'port' => '5530','descripcion' => 'Clinica Paredes','db' => 'Compuconta','url' => 'http://activos-paredes.compuconta.co', 'version' => 'CC3'],
                ['nombre' => 'ALC_CONSACA', 'ip' => '10.142.0.5', 'port' => '5531','descripcion' => 'Alcaldia Municipal de Consaca','db' => 'sistema','url' => 'https://alcaldia-consaca.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'AGUAS_DEL_GUILQUE', 'ip' => '10.142.0.5', 'port' => '5532','descripcion' => 'Aguas del Guilque','db' => 'sistema','url' => 'http://aguas-guilque.compuconta.co', 'version' => 'CC2'],
                ['nombre' => 'IPS_GUAITARA', 'ip' => '10.142.0.5', 'port' => '5533','descripcion' => 'IPS Guaitara => Infraestructura','db' => 'Compuconta','url' => 'https://ipsguaitara.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'LIDIA_MONTALVO', 'ip' => '10.142.0.5', 'port' => '5534','descripcion' => 'Lidia Montalvo','db' => 'sistema','url' => 'https://lidiamontalvo.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_GUAITARILLA', 'ip' => '10.142.0.5', 'port' => '5535','descripcion' => 'Alcaldia Municipal de Guaitarilla','db' => 'sistema','url' => 'https://alcaldia-guaitarilla.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_YACUANQUER', 'ip' => '10.142.0.5', 'port' => '5537','descripcion' => 'Alcaldia Municipal de Yacuanquer','db' => 'sistema','url' => 'http://alcaldia-yacuanquer.compuconta.co/', 'version' => 'CC2'],
                ['nombre' => 'ASOMPASC', 'ip' => '10.142.0.5', 'port' => '5538','descripcion' => 'Asompasc','db' => 'Compuconta','url' => 'http://asompasc.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'INGELEC', 'ip' => '10.142.0.5', 'port' => '5539','descripcion' => 'Ingelec','db' => 'Compuconta','url' => 'https://ingelec.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'UNION_SALUD_CC3', 'ip' => '10.142.0.5', 'port' => '5540','descripcion' => 'Union Salud - Facturacion electronica','db' => 'Compuconta','url' => 'https://ipsunionsalud.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'LAUNION_CC3', 'ip' => '10.142.0.5', 'port' => '5542','descripcion' => 'Industria y Ccio Munipio la Union','db' => 'Compuconta','url' => 'https://iyclaunion.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'CAPACITACIONESCC2', 'ip' => '10.142.0.5', 'port' => '5543','descripcion' => 'Capacitaciones Compuconta2','db' => 'sistema','url' => 'https://capacitaciones.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_TAMINANGO', 'ip' => '10.142.0.5', 'port' => '5545','descripcion' => 'Alcaldia Municipal de Taminango','db' => 'sistema','url' => 'https://alcaldia-taminango.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_CARTAGO', 'ip' => '10.142.0.5', 'port' => '5547','descripcion' => 'Alcaldia Municipal de Cartago','db' => 'sistema','url' => 'https://alcaldia-cartago.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_BARBACOAS', 'ip' => '10.142.0.5', 'port' => '5548','descripcion' => 'Alcaldia Municipal de Barbacoas','db' => 'sistema','url' => 'https://alcaldia-barbacoas.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_ARBOLEDA', 'ip' => '10.142.0.5', 'port' => '5549','descripcion' => 'Alcaldia Municipal de Arboleda','db' => 'sistema','url' => 'https://alcaldia-arboleda.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_LATOLA', 'ip' => '10.142.0.5', 'port' => '5550','descripcion' => 'Alcaldia Municipal de la Tola','db' => 'sistema','url' => 'https://alcaldia-tola.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_MAGUIPAYAN', 'ip' => '10.142.0.5', 'port' => '5551','descripcion' => 'Alcaldia Municipal de Magui Payan','db' => 'sistema','url' => 'https://alcaldia-maguipayan.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_ISCUANDE', 'ip' => '10.142.0.5', 'port' => '5552','descripcion' => 'Alcaldia Municipal de Iscuande','db' => 'sistema','url' => 'https://alcaldia-iscuande.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_OLAYAHERRERA', 'ip' => '10.142.0.5', 'port' => '5553','descripcion' => 'Alcaldia Municipal de Olaya Herrera','db' => 'sistema','url' => 'https://alcaldia-olayaherrera.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ESP-SANPABLO', 'ip' => '10.142.0.5', 'port' => '5554','descripcion' => 'ESP San Pablo','db' => 'sistema','url' => 'https://esp-emsanpablo.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_GUAITARILLA_CC3', 'ip' => '10.142.0.5', 'port' => '5535','descripcion' => 'Alcaldia Municipal de Guaitarilla - Activos fijos','db' => 'Compuconta','url' => 'https://alcaldia-guaitarilla-cc3.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ECTINAR', 'ip' => '10.142.0.5', 'port' => '5556','descripcion' => 'Eticnar','db' => 'sistema','url' => 'https://eticnar.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_COLONGENOVA', 'ip' => '10.142.0.5', 'port' => '5557','descripcion' => 'Alcaldia Municipal de Colon Genova','db' => 'sistema','url' => 'https://alcaldia-colongenova.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_VALLEGUAMUEZ', 'ip' => '10.142.0.5', 'port' => '5558','descripcion' => 'Alcaldia Valle del Guamuez','db' => 'sistema','url' => 'https://alcaldia-valleguamuez.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_LINARES', 'ip' => '10.142.0.5', 'port' => '5559','descripcion' => 'Alcaldia Municipal de Linares','db' => 'sistema','url' => 'https://alcaldia-linares.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'JULIAN_POSSOS', 'ip' => '10.142.0.5', 'port' => '5560','descripcion' => 'Julian Possos','db' => 'sistema','url' => 'https://julianpossos.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'SINDAWA', 'ip' => '10.142.0.5', 'port' => '5561','descripcion' => 'Asociación de Territorios Ancestrales Sindawa','db' => 'sistema','url' => 'https://asociacion-sindawa.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'IPS_IMALLAMAS_CC3', 'ip' => '10.142.0.5', 'port' => '5562','descripcion' => 'IPS Indigena Mallamas CC3','db' => 'Compuconta','url' => 'https://ips-mallamas-cc3.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ALC_TAMBO', 'ip' => '10.142.0.5', 'port' => '5563','descripcion' => 'Alcaldía Municipal El Tambo','db' => 'sistema','url' => 'https://alcaldia-tambo.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ECTINAR_CC3', 'ip' => '10.142.0.5', 'port' => '5556','descripcion' => 'Eticnar CC3','db' => 'Compuconta','url' => 'https://eticnar-cc3.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ALC_NARINO', 'ip' => '10.142.0.5', 'port' => '5564','descripcion' => 'Alcaldia Municipal de Nariño','db' => 'sistema','url' => 'https://alcaldia-narino.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ESE_SAULQUIÑONES', 'ip' => '10.142.0.5', 'port' => '5565','descripcion' => 'ESE Saul Quiñones','db' => 'sistema','url' => 'https://ese-saulquinones.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_ROBERTOPAYAN', 'ip' => '10.142.0.5', 'port' => '5567','descripcion' => 'Alcaldia Municipal de Roberto Payan','db' => 'sistema','url' => 'https://alcaldia-robertopayan.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ESE_SAGRADOCORAZON_CC3', 'ip' => '10.142.0.5', 'port' => '5568','descripcion' => 'ESE Sagrado Corazon de Jesus','db' => 'Compuconta','url' => 'https://ese-sagrado-corazon.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ALC_SAMANIEGO_CC3', 'ip' => '10.142.0.5', 'port' => '5569','descripcion' => 'Alcaldia Municipal de Samaniego Infraestructura CC3','db' => 'Compuconta','url' => 'https://alcaldia-samaniego.compuconta.com', 'version' => 'CC3'],
                ['nombre' => 'ESP_ANCUYA', 'ip' => '10.142.0.5', 'port' => '5570','descripcion' => 'ESP Ancuya','db' => 'Compuconta','url' => 'https://esp-ancuya.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_LAUNION', 'ip' => '10.142.0.5', 'port' => '5571','descripcion' => 'Alcaldia Municipal de La Union','db' => 'sistema','url' => 'https://alcaldia-launion.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_POTOSI', 'ip' => '10.142.0.5', 'port' => '5572','descripcion' => 'Alcaldia Municipal de Potosí','db' => 'sistema','url' => 'https://alcaldia-potosi.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'IPS_VIDAENCASA', 'ip' => '10.142.0.11', 'port' => '5573','descripcion' => 'IPS Vida en Casa','db' => 'sistema','url' => 'https://ips-vidaencasa.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'BOMBEROS_PASTO', 'ip' => '10.142.0.5', 'port' => '5574','descripcion' => 'Cuerpo Bomberos Voluntarios de Pasto','db' => 'Compuconta','url' => 'https://pys-bomberospasto.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'CT_REENCONTRARSE', 'ip' => '10.142.0.11', 'port' => '5432','descripcion' => 'Centro Terapeutico Reencontrarse','db' => 'sistema','url' => 'https://ctr.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'TRANSGUAMUEZ', 'ip' => '10.142.0.5', 'port' => '5579','descripcion' => 'Transguamuez S.A','db' => 'Compuconta','url' => 'https://transguamuez.compuconta.com', 'version' => 'CC3'],
                ['nombre' => 'ALC-SANMIGUEL', 'ip' => '10.142.0.5', 'port' => '5646','descripcion' => 'Alcaldia Municipal de San Miguel','db' => 'sistema','url' => 'https://alcaldia-miguel.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC-ELPENOL', 'ip' => '10.142.0.5', 'port' => '5432','descripcion' => 'Alcaldia Municipal de El Penol','db' => 'sistema','url' => 'https://alcaldia-penol.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_SAPUYES', 'ip' => '10.142.0.5', 'port' => '5546','descripcion' => 'Alcaldía Municipal De Sapuyes','db' => 'sistema','url' => 'https://alcaldia-sapuyes.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC-SANLORENZO', 'ip' => '10.142.0.5', 'port' => '5639','descripcion' => 'Alcaldia Municipal De San Lorenzo','db' => 'sistema','url' => 'https://alcaldia-lorenzo.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_TANGUA', 'ip' => '10.142.0.5', 'port' => '5594','descripcion' => 'Alcaldia Municipal De Tangua','db' => 'sistema','url' => 'https://alcaldia-tangua.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_CUMBAL', 'ip' => '10.142.0.5', 'port' => '5642','descripcion' => 'Alcaldia Municipal De Cumbal','db' => 'sistema','url' => 'https://alcaldia-cumbal.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC-TUQUERRES-CC2', 'ip' => '10.142.0.5', 'port' => '5648','descripcion' => 'Alcaldia Municipal de Tuquerres CC2','db' => 'sistema','url' => 'https://alcaldia-tuquerres-cc2.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC-CUMBITARA', 'ip' => '10.142.0.5', 'port' => '5596','descripcion' => 'Alcaldia Municipal De Cumbitara','db' => 'sistema','url' => 'https://alcaldia-cumbitara.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC-GUACHUCAL', 'ip' => '10.142.0.5', 'port' => '5597','descripcion' => 'Alcaldia Municipal de Guachucal','db' => 'sistema','url' => 'https://alcaldia-guachucal.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC-LACRUZ', 'ip' => '10.142.0.5', 'port' => '5595','descripcion' => 'Alcaldia Municipal De La Cruz','db' => 'sistema','url' => 'https://alcaldia-cruz.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC-PUPIALES', 'ip' => '10.142.0.5', 'port' => '5599','descripcion' => 'Alcaldia Municipal De Pupiales','db' => 'sistema','url' => 'https://alcaldia-pupiales.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ESE-ANCUYA', 'ip' => '10.142.0.5', 'port' => '5598','descripcion' => 'Centro De Salud Ancuya E.S.E','db' => 'sistema','url' => 'https://ese-ancuya.compuconta.com/clave.php', 'version' => 'CC2'],
                ['nombre' => 'IEM-NORMAL', 'ip' => '10.142.0.5', 'port' => '5600','descripcion' => 'Iem Normal Superior De Pasto','db' => 'sistema','url' => 'https://iem-normal.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM-LIBERTAD', 'ip' => '10.142.0.5', 'port' => '5601','descripcion' => 'Iem Libertad','db' => 'sistema','url' => 'https://iem-libertad.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM-CIUDADDEPASTO', 'ip' => '10.142.0.5', 'port' => '5602','descripcion' => 'Institucion Educativa Municipal Ciudad De Pasto','db' => 'sistema','url' => 'https://iem-ciudaddepasto.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'CLI_PAREDES', 'ip' => '10.142.0.5', 'port' => '5644','descripcion' => 'Clinica Oftalmologica Paredes','db' => 'sistema','url' => ' https://paredes-cc2.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ESP_EMMAGUI', 'ip' => '10.142.0.5', 'port' => '5575','descripcion' => 'EMPRESA DE ACUEDUCTO, ALCANTARILLADO Y ASEO E.S.P DEL MUNIICIPIO DE MAGUI PAYAN S.A.S EMMAGUI E.S.P SAS','db' => 'sistema','url' => 'https://emmagui.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ESE_SCJ_CHARCO', 'ip' => '10.142.0.5', 'port' => '5576','descripcion' => 'Hospital Sagrado Corazon de Jesus E.S.E. Charco','db' => 'sistema','url' => 'https://ese-scjcharco.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IPS_VIDAENCASA_CC3', 'ip' => '10.142.0.5', 'port' => '5578','descripcion' => 'IPS Vida en Casa CC3','db' => 'Compuconta','url' => 'https://vidaencasa-cc3.compuconta.com', 'version' => 'CC3'],
                ['nombre' => 'ESP_ROBERTO_PAYAN', 'ip' => '10.142.0.5', 'port' => '5580','descripcion' => 'Empresa de Servicios Publicos de Roberto Payan SAS','db' => 'sistema','url' => 'https://esp-roberto-payan.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'CLINICA_RETORNAR', 'ip' => '10.142.0.11', 'port' => '5502','descripcion' => 'Clinica Retornar','db' => 'sistema','url' => 'https://retornar.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'ALC_OSPINA', 'ip' => '10.142.0.5', 'port' => '5581','descripcion' => 'Alcaldia Municipal de Ospina','db' => 'sistema','url' => 'https://alcaldia-ospina.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'IPS_CONSTRUIMOSPRAGA', 'ip' => '10.142.0.5', 'port' => '5582','descripcion' => 'Construimos Praga SAS','db' => 'Compuconta','url' => 'https://construimos-praga.compuconta.com', 'version' => 'CC3'],
                ['nombre' => 'ALC-VALLEGUAMUEZ-CC3', 'ip' => '10.142.0.5', 'port' => '5558','descripcion' => 'Alcaldia Municipal del Valle del Guamuez CC3','db' => 'Compuconta','url' => 'https://alcaldia-valleguamuez-cc3.compuconta.com', 'version' => 'CC3'],
                ['nombre' => 'ALC_FUNES', 'ip' => '10.142.0.5', 'port' => '5585','descripcion' => 'Alcaldia de Funes CC3','db' => 'Compuconta','url' => 'https://alcaldia-funes.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ESE_LORENCITA_VILLEGAS', 'ip' => '10.142.0.5', 'port' => '5584','descripcion' => 'ESE Lorencita Villegas CC3','db' => 'Compuconta','url' => 'https://lorencitavillegas.compuconta.com', 'version' => 'CC3'],
                ['nombre' => 'EAAAP', 'ip' => '10.142.0.5', 'port' => '5586','descripcion' => 'Empresa De Acueducto Y Alcantarillado De Puerto Asis','db' => 'Compuconta','url' => 'https://eaaap.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'IEM_LUIS_EDUARDO_CC3', 'ip' => '10.142.0.5', 'port' => '5587','descripcion' => 'IEM Luis Eduardo Mora Osejo CC3','db' => 'Compuconta','url' => 'http://iemluiseduardomora-cc3.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'EPS_MALLAMAS', 'ip' => '10.142.0.5', 'port' => '5588','descripcion' => 'EPS Mallamas','db' => 'sistema','url' => 'https://eps-mallamas.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_PENOL', 'ip' => '10.142.0.5', 'port' => '5589','descripcion' => 'Alcaldia del Peñol','db' => 'sistema','url' => 'https://alcaldia-penol.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ESE_FRONTERIZO-DORADA', 'ip' => '10.142.0.5', 'port' => '5590','descripcion' => 'E.S.E Hospital Fronterizo La Dorada','db' => 'Compuconta','url' => 'https://ese-fronterizodorada.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ESE_LUIS-ACOSTA', 'ip' => '10.142.0.5', 'port' => '5591','descripcion' => 'Centro de salud Municipal nivel I Luis Acosta E.S.E','db' => 'Compuconta','url' => 'https://ese-luisacosta.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ESE_SAGRADOCORAZON_CC2', 'ip' => '10.142.0.5', 'port' => '5592','descripcion' => 'Ese Sagrado Corazon de Jesus CC2','db' => 'Compuconta','url' => 'https://ese-sagrado-corazonCC2.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC_CHARCO', 'ip' => '10.142.0.5', 'port' => '5593','descripcion' => 'Alcaldía Del Charco','db' => 'sistema','url' => 'https://alcaldia-charco.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ESE_ISCUANDE', 'ip' => '10.142.0.5', 'port' => '5504','descripcion' => 'E.S.E Santa Barbara de Iscuande','db' => 'sistema','url' => 'https://ese-iscuande.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'IEM_TECNICO-INDUSTRIAL', 'ip' => '10.142.0.5', 'port' => '5603','descripcion' => 'Iem Tecnico Industrial','db' => 'sistema','url' => 'https://iem-tecnico-industrial.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_SANTA-BARBARA', 'ip' => '10.142.0.5', 'port' => '5605','descripcion' => 'Iem Santa Barbara','db' => 'sistema','url' => 'https://iem-santa-barbara.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_ARTEMIO-MENDOZA', 'ip' => '10.142.0.5', 'port' => '5606','descripcion' => 'Iem Artemio Mendoza Carvajal','db' => 'sistema','url' => 'https://iem-artemio-mendoza.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_MERCEDARIO', 'ip' => '10.142.0.5', 'port' => '5607','descripcion' => 'Iem Mercedario','db' => 'sistema','url' => 'https://iem-mercedario.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_AUERLIO-ARTURO', 'ip' => '10.142.0.5', 'port' => '5608','descripcion' => 'Iem Aurelio Arturo Martinez','db' => 'sistema','url' => 'https://iem-auerlio-arturo.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_ANTONIO-NARIÑO', 'ip' => '10.142.0.5', 'port' => '5609','descripcion' => 'Iem Antonio Nariño','db' => 'sistema','url' => 'https://iem-antonio-narino.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_POPULAR', 'ip' => '10.142.0.5', 'port' => '5610','descripcion' => 'Iem Centro De Integracion Popular','db' => 'sistema','url' => 'https://iem-popular.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_CHAMBU', 'ip' => '10.142.0.5', 'port' => '5611','descripcion' => 'Iem Chambu','db' => 'sistema','url' => 'https://iem-chambu.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_LUIS-EDUARDO-MORA', 'ip' => '10.142.0.5', 'port' => '5612','descripcion' => 'Iem Luis Eduardo Mora Osejo CC2','db' => 'sistema','url' => 'https://iem-luis-eduardo-mora.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'CEM_JAMONDINO', 'ip' => '10.142.0.5', 'port' => '5613','descripcion' => 'Cem Jamondino','db' => 'sistema','url' => 'https://cem-jamondino.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_CIUDADELA-PASTO', 'ip' => '10.142.0.5', 'port' => '5614','descripcion' => 'Iem Ciudadela Educativa De Pasto','db' => 'sistema','url' => 'https://iem-ciudadela-pasto.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_MORASURCO', 'ip' => '10.142.0.5', 'port' => '5615','descripcion' => 'Iem Morasurco','db' => 'sistema','url' => 'https://iem-morasurco.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_GUALMATAN', 'ip' => '10.142.0.5', 'port' => '5616','descripcion' => 'Iem Gualmatan','db' => 'sistema','url' => 'https://iem-gualmatan.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_SEÑORA-VISITACION', 'ip' => '10.142.0.5', 'port' => '5617','descripcion' => 'Iem Nuestra Señora De La Visitacion ','db' => 'sistema','url' => 'https://iem-senora-visitacion.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_CRISTO-REY', 'ip' => '10.142.0.5', 'port' => '5618','descripcion' => 'Iem Cristo Rey','db' => 'sistema','url' => 'https://iem-cristo-rey.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_MARCO-FIDEL-SUAREZ', 'ip' => '10.142.0.5', 'port' => '5619','descripcion' => 'Iem Marco Fidel Suarez','db' => 'sistema','url' => 'https://iem-marco-fidel-suarez.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_CABRERA', 'ip' => '10.142.0.5', 'port' => '5620','descripcion' => 'Iem Cabrera','db' => 'sistema','url' => 'https://iem-cabrera.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_AGUSTIN-AGUALONGO', 'ip' => '10.142.0.5', 'port' => '5621','descripcion' => 'Iem Agustin Agualongo','db' => 'sistema','url' => 'https://iem-agustin-agualongo.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_FRANCISCO-VILLOTA', 'ip' => '10.142.0.5', 'port' => '5622','descripcion' => 'Iem Francisco De La Villota','db' => 'sistema','url' => 'https://iem-francisco-villota.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_CALDERA', 'ip' => '10.142.0.5', 'port' => '5623','descripcion' => 'Iem La Caldera','db' => 'sistema','url' => 'https://iem-caldera.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_JOSE-ANTIONIO-GALAN', 'ip' => '10.142.0.5', 'port' => '5624','descripcion' => 'Iem Jose Antonio Galan','db' => 'sistema','url' => 'https://iem-jose-antionio-galan.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'CEM_ANGELES', 'ip' => '10.142.0.5', 'port' => '5625','descripcion' => 'Cem Los Angeles','db' => 'sistema','url' => 'https://cem-angeles.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_SOCORRO', 'ip' => '10.142.0.5', 'port' => '5626','descripcion' => 'Iem El Socorro','db' => 'sistema','url' => 'https://iem-socorro.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_FRANCISCO-ASIS', 'ip' => '10.142.0.5', 'port' => '5627','descripcion' => 'Iem San Francisco De Asis','db' => 'sistema','url' => 'https://iem-francisco-asis.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_GUADALUPE', 'ip' => '10.142.0.5', 'port' => '5628','descripcion' => 'Iem Nuestra Señora De Guadalupe','db' => 'sistema','url' => 'https://iem-guadalupe.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'CEM_CAMPANERO', 'ip' => '10.142.0.5', 'port' => '5629','descripcion' => 'Cem Campanero','db' => 'sistema','url' => 'https://cem-campanero.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_EDUARDO-ROMO-ROSERO', 'ip' => '10.142.0.5', 'port' => '5630','descripcion' => 'Iem Eduardo Romo Rosero','db' => 'sistema','url' => 'https://iem-eduardo-romo-rosero.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_SANTA-TERESITA-CATAMBUCO', 'ip' => '10.142.0.5', 'port' => '5631','descripcion' => 'Iem Santa Teresita (Catambuco)','db' => 'sistema','url' => 'https://iem-santa-teresita-catambuco.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_LA-VICTORIA', 'ip' => '10.142.0.5', 'port' => '5632','descripcion' => 'Iem La Victoria','db' => 'sistema','url' => 'https://iem-la-victoria.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_PEDAGOGICO', 'ip' => '10.142.0.5', 'port' => '5633','descripcion' => 'Iem Pedagogico','db' => 'sistema','url' => 'https://iem-pedagogico.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_CIUDADELA-PAZ', 'ip' => '10.142.0.5', 'port' => '5634','descripcion' => 'Iem Ciudadela De La Paz','db' => 'sistema','url' => 'https://iem-ciudadela-paz.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_ENCANO', 'ip' => '10.142.0.5', 'port' => '5635','descripcion' => 'Iem El Encano','db' => 'sistema','url' => 'https://iem-encano.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'CEM_SANTA-TERESITA-ENCANO', 'ip' => '10.142.0.5', 'port' => '5636','descripcion' => 'Cem Santa Teresita (El Encano)','db' => 'sistema','url' => 'https://cem-santa-teresita-encano.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_FRANCISCO-JOSE', 'ip' => '10.142.0.5', 'port' => '5637','descripcion' => 'Iem Francisco Jose De Caldas','db' => 'sistema','url' => 'https://iem-francisco-jose.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'IEM_OBONUCO', 'ip' => '10.142.0.5', 'port' => '5638','descripcion' => 'Iem Obonuco','db' => 'sistema','url' => 'https://iem-obonuco.compuconta.com', 'version' => 'CC2'],
                ['nombre' => 'RES_GUALCALA', 'ip' => '10.142.0.5', 'port' => '5640','descripcion' => 'Resguardo Indigena Gualcala','db' => 'sistema','url' => 'https://resguardo-gualcala.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'IEM_LICEO-NARINO', 'ip' => '10.142.0.5', 'port' => '5643','descripcion' => 'IEM Liceo Central de Nariño','db' => 'sistema','url' => 'https://iem-liceo-narino.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ESE_LOURDES_CC3', 'ip' => '10.142.0.5', 'port' => '5645','descripcion' => 'E.S.E Centro de salud Virgen de Lourdes Buesaco (Almacen)','db' => 'Compuconta','url' => 'https://ese-virgen-lourdes.compuconta.com/', 'version' => 'CC3'],
                ['nombre' => 'ESE_TOLA', 'ip' => '10.142.0.5', 'port' => '5647','descripcion' => 'Ese de la Tola','db' => 'sistema','url' => 'https://ese-tola.compuconta.com/', 'version' => 'CC2'],
                ['nombre' => 'ALC-TUQUERRES-CC3', 'ip' => '10.142.0.5', 'port' => '5649','descripcion' => 'Alcaldia Municipal de Tuquerres CC3','db' => 'Compuconta','url' => 'https://alcaldia-tuquerres-cc3.compuconta.com/', 'version' => 'CC3'],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
